### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by BenjaU2** [xinluo2018/WatNetv2#1]
Hello, I am using your code as a base and I have a problem, I would like to know how your dataset, training and validation data is distributed, I am trying to understand but I am getting lost, I would appreciate your response.

**Comment by xinluo2018** [comment]
hi, our dataset for WatNetv2 is still developing, if you just want to running this models in WatNetv2, you can use the dataset in https://zenodo.org/records/5205674, which is developed for the WatNet, but also appliable for the models in WatNetv2.
